### ISSUE TITLE
[BUG] API broken

### ISSUE THREAD

**Issue by relliv** [Electron-Store/electron-app-store#17]
**Describe the bug**

Some endpoints return empty respınse such as `https://api.electron-store.org/get-category-list?` and I think to explore feed API changed `https://api.electron-store.org/explore-feed?` because the logo field missing. Search endpoints blocking with CORS error.

Finally, UI is empty.

**Screenshots**
![image](https://user-images.githubusercontent.com/17010054/163662118-befd7b9d-aeae-41f9-b41e-4c1a94ac8e56.png)
![image](https://user-images.githubusercontent.com/17010054/163662129-fca2690c-b368-4338-81fe-1e2b0ce3a715.png)

**Desktop (please complete the following information):**
Edition	Windows 11 Pro
Version	21H2
Installed on	‎5.‎10.‎2021
OS build	22000.613
Experience	Windows Feature Experience Pack 1000.22000.613.0

**Comment by jdev082** [comment]
Issues:
Most icons do not load
Some applications do not appear

**Comment by isworking** [comment]
I've rewritten most (if not all) of the API and found out that the existing App Store isn't working with the new API. I'm currently working on the complete rewrite of the App Store to make it work with the new API. And with Icons, the CORS issue was preventing them from loading which has been fixed with the new API (`https://api.electron-store.org/app-img/:app`).

**Comment by isworking** [comment]
Also I found out that `/get-category-list` and `/explore-feed` endpoints need some fixes. I'll fix them push the latest commit soon.

**Comment by isworking** [comment]
Fixed with electron-store/electron-store-api@7b44d65
